services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: innoscripta-app
    container_name: innoscripta-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./apache2conf.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: innoscripta-db
    restart: always
    environment:
      MYSQL_DATABASE: innoscripta
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./innoscripta.sql:/docker-entrypoint-initdb.d/innoscripta.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: innoscripta-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "8080:80"

volumes:
  db_data: