version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: innoscripta-laravel
    container_name: innoscripta-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./apache2conf.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=innoscripta
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - innoscripta-network

  db:
    image: mysql:8.0
    container_name: innoscripta-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innoscripta
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./innoscripta.sql:/docker-entrypoint-initdb.d/innoscripta.sql
    command: 
      - --default-authentication-plugin=mysql_native_password
    networks:
      - innoscripta-network

  redis:
    image: redis:alpine
    container_name: innoscripta-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - innoscripta-network

volumes:
  db_data:

networks:
  innoscripta-network:
    driver: bridge